# Generated by Django 4.0.10 on 2023-09-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
